version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: comments
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      USE_IN_MEMORY: "false"
      DATABASE_URL: "postgres://postgres:postgres@db:5432/comments?sslmode=disable"
    depends_on:
      - db
